#!/usr/bin/env bash
#This script uses a `while` loop to read through the file `/etc/passwd` line by line. 
IFS=':'

while read -r username password uid gid gecos home shell
do
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $gecos"
done < /etc/passwd
