#!/usr/bin/env bash
# Display "best School" 10 times plus "Hi"

counter=1
while [ $counter -le 10 ]
do
    echo "best School"
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    fi
    ((counter++))
done
